[package]
name = "airguitar"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libmdns = "0.6"
tokio = { version = "1.12", features = ["full"] }
